// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * Drawing primitive (#154): per-author, per-map markup overlays.
 *
 * A drawing set is owned by an author (or null for anonymous public
 * markups), carries its own color so multiple authors are visually
 * distinguishable at a glance, and renders on top of every data
 * layer in the map. Drawings are NOT data layers and are NOT shared
 * via the layer panel; they live in a dedicated Markup pane in the
 * editor.
 *
 * Authoring posture: any signed-in viewer with view access to a
 * map can create their own drawing set. Anonymous public viewers
 * can do the same when the map's `allowAnonymousDrawings` flag is
 * on (off by default). Authors can edit / delete their own set;
 * admins of the map's item can edit / delete any set. This unlocks
 * the "manager opens a shared map and redlines it" workflow without
 * editor permission on the underlying map.
 *
 * Phase 1 stores drawings inline on the map's data_json. Two
 * concurrent edits to the same drawing set last-write-wins; the
 * collaborative-edit story (Phase 2 + live cursors) layers a CRDT
 * on top of this same shape so the storage format does not change.
 */
import type { DashStyle } from './map';

/**
 * A single marker / annotation inside a drawing set.
 *
 * `kind` is the AUTHORING intent ("the user picked the pin tool")
 * even though the GeoJSON `geometry` already tells you the shape.
 * Keeping both lets the UI group features by tool used and lets the
 * renderer choose between rendering modes that geometry alone cannot
 * disambiguate (a `text` annotation and a `pin` annotation both have
 * Point geometry but render very differently).
 */
export interface DrawingFeature {
  /**
   * Stable UUID. The Phase 2 comments work pins comment threads to
   * `parentRef.id === drawingFeature.id`, so this id has to survive
   * edits to the geometry / style / label.
   */
  id: string;
  kind: 'pin' | 'line' | 'polygon' | 'text' | 'arrow' | 'circle';
  /** GeoJSON geometry. Point for pin / text, LineString for line /
   *  arrow, Polygon for polygon / circle (circle is materialised
   *  as a 32-segment polygon when the user finishes the tool). */
  geometry: unknown;
  /**
   * Per-feature style overrides. Anything left unset inherits from
   * the parent drawing set's color + the renderer defaults. Kept
   * narrow on purpose: drawings are markup, not symbology, so the
   * full MapLayerStyle vocabulary would be overkill.
   */
  style?: {
    color?: string;
    strokeWidth?: number;
    dashStyle?: DashStyle;
    fillOpacity?: number;
  };
  /** Optional label rendered above the geometry. */
  label?: string;
  /** Free-text note attached to the feature. The Phase 2 threaded-
   *  comments work supersedes this with a real thread; until then,
   *  it's a simple single-string note for fast scribbling. */
  note?: string;
  createdAt: string;
  updatedAt: string;
}

export interface DrawingSet {
  id: string;
  /**
   * Author user id, or null for anonymous public viewers. The portal
   * API resolves the display name at write time so the renderer
   * never needs a user lookup just to label a redline. Display name
   * comes from the user's profile name; anonymous sets fall back to
   * a stable per-set label like "Anonymous reviewer 1".
   */
  authorId: string | null;
  authorDisplay: string;
  /** Human-readable title. Auto-generated by the UI at create time
   *  ("Matt's markup 2026-05-30") and freely editable thereafter. */
  title: string;
  /**
   * Hex color shared by every feature in this set unless overridden.
   * Auto-assigned at create time from DRAWING_SET_PALETTE so two
   * concurrent reviewers get visually distinct colors.
   */
  color: string;
  /** Show / hide toggle. Persisted per-set so a viewer can hide
   *  someone else's markup without affecting other viewers. */
  visible: boolean;
  features: DrawingFeature[];
  createdAt: string;
  updatedAt: string;
}

/**
 * Auto-color palette for new drawing sets. Cycles based on the
 * count of existing sets so two concurrent reviewers get distinct
 * colors out of the box. Chosen for distinctness on both light and
 * dark basemaps and for accessibility (no two adjacent colors are
 * indistinguishable for the common red-green color vision
 * deficiencies).
 */
export const DRAWING_SET_PALETTE: string[] = [
  '#ef4444', // red
  '#f97316', // orange
  '#eab308', // amber
  '#22c55e', // green
  '#06b6d4', // cyan
  '#3b82f6', // blue
  '#8b5cf6', // violet
  '#ec4899', // pink
];

/**
 * Pick the next color for a new drawing set given the colors already
 * in use. Walks the palette in order; first un-used color wins. If
 * every palette color is in use, cycles back to the first (so the
 * Nth set just doubles up rather than blocking the create).
 */
export function nextDrawingSetColor(usedColors: string[]): string {
  const used = new Set(usedColors.map((c) => c.toLowerCase()));
  for (const c of DRAWING_SET_PALETTE) {
    if (!used.has(c.toLowerCase())) return c;
  }
  return DRAWING_SET_PALETTE[
    usedColors.length % DRAWING_SET_PALETTE.length
  ]!;
}

/**
 * Default title for a freshly-created drawing set. Renders as
 * "<author>'s markup <date>" so the Markup pane reads as a stack of
 * dated review rounds without the author having to think about
 * naming. The date is the viewer's local date in ISO form
 * (YYYY-MM-DD); the timezone is the viewer's.
 */
export function defaultDrawingSetTitle(
  authorDisplay: string,
  now: Date = new Date(),
): string {
  const yyyy = now.getFullYear();
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const dd = String(now.getDate()).padStart(2, '0');
  return `${authorDisplay}'s markup ${yyyy}-${mm}-${dd}`;
}
